repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: change-repo-name

  # A short description of the repository that will show up on GitHub
  description: description of repo
